### ISSUE TITLE
guys plz read this

### ISSUE THREAD

**Issue by DeveloperSa1** [sensepost/mana#105]
# Deprecation Notice
Hey guys 
I've just installed " mana " 
I been trying to start-nat-full.sh But nothing i got this error ( bash: ./start-nat-full.sh: No such file or directory ) I'm really confused 
cd /usr/share/mana-toolkit > then
cd run-mana > then
when I commended " ls " 
nothing showed up > why is that?
Pls help ..
Thanks in advance

**Comment by DeveloperSa1** [comment]
anyone help plzzzzz

**Comment by singe** [comment]
Looks like it didn't install properly, there should be files in that directory. That's not unexpected given this is no longer supported or maintained.

**Comment by DeveloperSa1** [comment]
thanks it worked for me , I did " apt-get install mana-toolkit "
