### ISSUE TITLE
Noupstream portal not working correctly and missing Facebook site

### ISSUE THREAD

**Issue by 0ut0fb0unds** [sensepost/mana#11]
I am able to use the start-noupstream.sh script and create an access point successfully.

Using Safari on an iPhone, sites like gmail.com, twitter.com, facebook.com say "Safari cannot open the page because it could not establish a secure connection to the server." I am assuming this is due to HSTS, is there any way to serve these sites the captive portal? Or redirect a site like gmail.com to the google sign in page?

Also when I start the script, after it starts the apache2dnsspoof service I see this:

`Warning: DocumentRoot [/usr/share/mana-toolkit/www/facebook] does not exist`

I'm assuming I can either create a fake Facebook site or remove the facebook.conf file from the Apache sites-available directory to remove the warning, is that correct?

**Comment by N2Network** [comment]
0ut0fb0unds,

Can you explain how you fixed Apache from displaying the default site?

"Thanks. I was able to figure out the apache default site issue and got that working."
