### ISSUE TITLE
HostAPD could not configure driver mode

### ISSUE THREAD

**Issue by hpsauce** [sensepost/mana#13]
Hello,

Using builtin wlan0 and an external Alfa NHA as wlan1, starting up shows the following errors:-

nl80211: could not configure driver mode
nl80211: driver initialisation failed
hostapd_free_hapd_data: interface wlan1 wasn't started

service network-manager stop has been commented out from the startup script.

Any clues? 
Ubuntu 14.04

**Comment by singe** [comment]
hpsauce is spot on, I'm building that into a helper script to avoid blindly killing network manager in future.

**Comment by Bryantp757** [comment]
I have my wlan0 (alfa card connected) to a VM with Kali 2. I excluded wlan0 in the conf file but I continue to get this issue.

**Comment by Bryantp757** [comment]
root@kali2:/usr/share/mana-toolkit/run-mana# ./start-nat-simple.sh
Configuration file: /etc/mana-toolkit/hostapd-karma.conf
nl80211: Could not configure driver mode
nl80211 driver initialization failed.
hostapd_free_hapd_data: Interface wlan0 wasn't started
Internet Systems Consortium DHCP Server 4.3.1
Copyright 2004-2014 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /etc/mana-toolkit/dhcpd.conf
Database file: /var/lib/dhcp/dhcpd.leases
PID file: /var/run/dhcpd.pid
Wrote 0 leases to leases file.
Listening on LPF/wlan0/00:c0:ca:53:32:9f/10.0.0.0/24
Sending on   LPF/wlan0/00:c0:ca:53:32:9f/10.0.0.0/24
Sending on   Socket/fallback/fallback-net
Hit enter to kill me

**Comment by raphaelraj1035** [comment]
Does anyone solved this? facing the same issue? 
Configuration file: /etc/mana-toolkit/hostapd-mana.conf
nl80211: Could not configure driver mode
nl80211 driver initialization failed.
hostapd_free_hapd_data: Interface wlan0 wasn't started
Hit enter to kill me

**Comment by singe** [comment]
Most likely cause, something is using your interface, most often network-manager. 

airmon-ng check
Can show you what’s using it.

**Comment by Shubham3314** [comment]
Hey i am getting the same error while i use mana-toolkit 

I have changed the phy = wlan0 in the start-nat-simple.sh 

I have killed all the process using airmon-ng check kill 

But i getting the same error 
Configuration file: /etc/mana-toolkit/hostapd-mana.conf
 nl80211: Could not configure driver mode
 nl80211 driver initialization failed.
 hostapd_free_hapd_data: Interface wlan0 wasn't started
 Hit enter to kill me

Anyone help plz 
Thanks
