### ISSUE TITLE
start-noupstream DNS Spoofing

### ISSUE THREAD

**Issue by safeasfcuk** [sensepost/mana#14]
Im relitivly new to linux and am having a few issues trying to work out how to achieve my goal.

I would like to use your scripts to host a no upstream based captive portal on a raspberry pi and log the credentials to a log file.

I have been using the default portal with some success after modifying the location of the default.conf
However i notice that apple.com and google.com will not be directed to the portal instead its directed to the google and apple folder. Whilst i see the logic in this i would like to direct all sites to my default portal however I'm struggling to find the location of the file to edit. 

Could you point me in the best direction please?

**Comment by singe** [comment]
The apple and google redirects are necessary to fool devices into thinking they're online. You can either edit the google.conf and apple.conf in /etc/apache2/sites-enabled/ or the actual content in /var/www/google /var/www/apple

Does this resolve your question?
