### ISSUE TITLE
wwww issue on IPhone

### ISSUE THREAD

**Issue by zoneoutaussie** [sensepost/mana#15]
Hello,

I am trying out mana and love it however on iPhone with Safari when logging into a secure page you can see sslstrip change the domain to wwww.example but then either the page displays only the text minus images and CSS or not page at all.

I am using a clean install of Kali and installed mana-toolkit via apt-get and using start-nat-full.ssh

**Comment by singe** [comment]
I haven't experienced that myself. Can you give an example site and/or try with the latest sslstrip I've updated to?
