### ISSUE TITLE
Driver issue Alfa AWUS036NHA

### ISSUE THREAD

**Issue by one2k** [sensepost/mana#16]
Hi guys,

As opposed to my build-in wifi (Macbook Air 2012) I cant get my **Alfa AWUS036NHA** usb wifi adapter working with mana.

**Using driver nl80211 it states in the terminal:**
nl80211: Could not configure driver mode
nl80211 driver initialization failed.
hostapd_free_hapd_data: Interface wlan3 wasn't started
Configuration file: /etc/mana-toolkit/hostapd-karma.conf

**Whereas using the rtl8187 driver start-nat-full.sh fails with:**
Configuration file: /etc/mana-toolkit/hostapd-karma.conf
Line 3: invalid/unknown driver 'rtl8187'
1 errors found in configuration file '/etc/mana-toolkit/hostapd-karma.conf'
Failed to set up interface with /etc/mana-toolkit/hostapd-karma.conf
Failed to initialize interface

OS: Kali Linux

Any idea on how to get this working properly?
Thank you very much and keep on the great work on this project!

**Comment by singe** [comment]
The nl driver error is most likely thanks to network-manager or the like interfering with the interface. Can you confirm its all yours and no other processes are messing with it (airmon-ng can help)?

As for the other error I don't think the rt driver is set to compile in the hostapd-mana config (or it's something silly like it's not spelled right). I've personally never used anything but nl and there may be dragons outside it.

Good luck!
singe

**Comment by one2k** [comment]
Turned out that a wpa_supplicant daemon running in the background unintentionally caused this error.
Thank you singe!

**Comment by Bryantp757** [comment]
I am having the same issue but I am not seeing a wpa_supplicant . How did you find this one?

**Comment by singe** [comment]
`airmon-ng check kill`

Will kill anything interfering.

**Comment by bluqboy** [comment]
i am getting the error and i used airmon-ng check kill 
but its not working
