### ISSUE TITLE
SSLStrip2

### ISSUE THREAD

**Issue by 7109node** [sensepost/mana#23]
The linked github for SSLstrip2 has been emptied by the creator due to Spanish gag law apparently.  Is there another source for those files to complete the mana toolkit?  I've done some digging and can't find anything.

**Comment by singe** [comment]
I made my own fork, rolled back the deletes and things look to be working fine again. Can you confirm?

**Comment by 7109node** [comment]
Brilliant.  Thanks for the quick response.
