### ISSUE TITLE
MSCHAPV2 GTC downgrade.

### ISSUE THREAD

**Issue by rkornmeyer** [sensepost/mana#24]
https://github.com/Torinson/lootbooty has been an incredible tool. Essentially any EAP type (with the exception of EAP-TLS w/ client side cert validation), it will give an MSCHAPv2 success response and then only accept GTC authentication. Any client that supports GTC will send credentials through the tunnel in cleartext rather than MSCHAP C/R. In networks that do not separate BYOD and corporate wireless this works VERY well. I was thinking it would be worthwhile to include it into mana. However, it looks as though its built upon freeradius and a patch that always sends an MSCHAPv2 success message. I was thinking that perhaps someone could translate that to hostapd, however based on my testing it would break hostapd. Perhaps use the patched freeradius as a submodule. The ruby script seems to only consist of editing the conf and only allowing GTC auth, the rest is pretty much outputting to a log file and grepping. However, it would probably be a great addition to mana.

**Comment by singe** [comment]
This is already built into brad's hostapd patch that I'll be merging. Thanks for the suggestion.

**Comment by singe** [comment]
This was added.

**Comment by dhd0004** [comment]
Hi,

Y am trying to make the GTC-Downgrade attack works with mana toolkit, but mana always responde with MSCHAPv2 to the Android Device.
There is any configuration option to make this kind of attack works?

RegardsHi,

Y am trying to make the GTC-Downgrade attack works with mana toolkit, but mana always responde with MSCHAPv2 to the Android Device.
There is any configuration option to make this kind of attack works?

Regards
