### ISSUE TITLE
Has anyone installed this recently with the install script ?

### ISSUE THREAD

**Issue by n0x00** [sensepost/mana#25]
I'm keen to speak to someone who's got this running on recent software. 

I have tried on Kali 1.0.8 and latest, and ubuntu 14.0.4.2 with the install scripts and I have had no success. 

the most frustrating thing is I've had this working until I dist-upgraded my old VM :'(

**Comment by singe** [comment]
Can you describe why it's not working in more detail and I can try help resolve that.

**Comment by n0x00** [comment]
it was failing with hostapd, tiny proxy and dhcp-isc ?* - I tried on old version of kali 1.0.8, 14.0.4 ubuntu and the latest kali all the same, lucky for me i have a old backup VM that works ! 

I'm a little defeated now, I have it working, on the old VM, happy to close this comment, i just figured someone else would have the same issue - it's no longer in apt in kali hostpad isnt building and 2 dependencies are also missing from kali - apt 

:(

**Comment by Jessexd** [comment]
dude, for real, this is not enough detail.

**Comment by n0x00** [comment]
Jess, I can only tell you what my error messages are telling me and that i've already said

 tinyproxy isn't available
 dhcp-isc isn't available
 libnl-dev isn't available
... and the apt-get install mana-toolkit is no longer available. 

I've tried on different versions of kal and supported versions of ubuntu and kali as per the install scripts 

but I've already said that

**Comment by Jessexd** [comment]
you are using wheezy right? arent mixing repos? amd64?

wget http://ftp.us.debian.org/debian/pool/main/libn/libnl/libnl-dev_1.1-7_amd64.deb http://ftp.us.debian.org/debian/pool/main/libn/libnl/libnl1_1.1-7_amd64.deb http://ftp.us.debian.org/debian/pool/main/t/tinyproxy/tinyproxy_1.8.3-3_amd64.deb http://ftp.us.debian.org/debian/pool/main/i/isc-dhcp/isc-dhcp-server_4.2.2.dfsg.1-5+deb70u6_amd64.deb http://ftp.us.debian.org/debian/pool/main/i/isc-dhcp/isc-dhcp-client_4.2.2.dfsg.1-5+deb70u6_amd64.deb

dppkg -i --force-overwrite libnl1_1.1-7_amd64.deb libnl1_1.1-7_amd64.deb tinyproxy_1.8.3-3_amd64.deb isc-dhcp-server_4.2.2.dfsg.1-5+deb70u6_amd64.deb isc-dhcp-client_4.2.2.dfsg.1-5+deb70u6_amd64.deb

**Comment by n0x00** [comment]
Hey Jess, I'll try that now on a fresh install

thanks for the help, I'll let you know how I get on

Nice one

**Comment by Jessexd** [comment]
if all else fails
wget http://ftp.cc.uoc.gr/mirrors/linux/kali/kali/pool/main/m/mana-toolkit/mana-toolkit_0~20140915-0kali1_amd64.deb
dpkg -i --force-overwrite mana-toolkit/mana-toolkit_0~20140915-0kali1_amd64.deb
apt-get install --fix-missing -f

**Comment by n0x00** [comment]
I have conflicts with libnl-dev still (the version mana needs isn't the one I have installed) 

I'm going to try your steps on an older version of Kali 1.0.8 as per the original install script, see how I get on !

**Comment by singe** [comment]
Can you try the latest version included in kali-rolling or the deb's in the last release.
