### ISSUE TITLE
hostapd doesn't show SSID's

### ISSUE THREAD

**Issue by Thanathan-k** [sensepost/mana#27]
When starting any of the mana-toolkit scripts, I don't get the names of the probed/responded SSID's. All my log is showing is (null):

    wlan0: STA xx:xx:xx:xx:xx:xx IEEE 802.11: authenticated

    wlan0: STA xx:xx:xx:xx:xx:xx IEEE 802.11: associated (aid 1)

    wlan0: AP-STA-CONNECTED xx:xx:xx:xx:xx:xx

    KARMA: Successful association of xx:xx:xx:xx:xx:xx to ESSID '(null)'

Any known fix to this? Or am I the only one with this problem?

**Comment by Thanathan-k** [comment]
It seems like the ssid_probe_karma attribute is not getting set correctly. Couldnt figure out why and where yet...

**Comment by singe** [comment]
I'll be releasing a big push that fixes this any several other issues on Wed.

**Comment by Thanathan-k** [comment]
Still geting the KARMA: Successful association of xx:xx:xx:xx:xx:xx to ESSID '(null)' after installing your new push.

**Comment by singe** [comment]
Ok, it really is fixed now:
MANA - Successful association of xx:xx:xx:xx:xx:xx to ESSID 'Internet'

One thing to check, even the previous commit used MANA instead of KARMA, double check you have the new code and have recompiled.
