### ISSUE TITLE
Apps are hit or miss

### ISSUE THREAD

**Issue by DrDinosaur** [sensepost/mana#3]
I have got this started with the full mode. Most things seem to be working pretty well. However, Internet connectivity with mobile applications tends not to work. A few work, but most of them don't have any connectivity. Sportsenter seemed to work, but most apps like Twitter, Facebook, Messenger, NBC News, Flipboard, Snapchat, OneDrive, Amazon, and Speedtest didn't work. Interestingly enough, pretty much everything through Chrome works fine (though there are the expected certificate errors). My hunch is that the issue lies with SSLsplit and SSLstrip. Both seem to be working as expected on my Kali box though.

**Comment by singe** [comment]
Any feedback? I'd like to close the issue if possible.

**Comment by DrDinosaur** [comment]
Wow sorry, this is really old. I will set a reminder for myself.
