### ISSUE TITLE
hostapd mana won't compile on Debian Jessie

### ISSUE THREAD

**Issue by thesle3p** [sensepost/mana#32]
Hi, It looks like Mana-hostapd is looking for libnl header files in places Debian Jessie does not keep them. Bellow is the error message I get when I try and compile Mana: 

make -C hostapd-mana/hostapd/
make[1]: Entering directory '/base/dir/mana/hostapd-mana/hostapd'
../src/drivers/driver_nl80211.c:19:27: fatal error: netlink/fgenl.h: No such file or directory
 #include <netlink/fgenl.h>
                           ^
compilation terminated.
Makefile:891: recipe for target '../src/drivers/driver_nl80211.o' failed
make[1]: *** [../src/drivers/driver_nl80211.o] Error 1
make[1]: Leaving directory ''/base/dir/mana/hostapd-mana/hostapd'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2

I guess update the make file to know where to find fgenl.h?

**Comment by singe** [comment]
Do you have libnl-dev installed? What other netlink dev packages do you have installed? I've not tried on Debian, are you running sid or other?

**Comment by thesle3p** [comment]
I have libnl-dev installed and As I said I am running Debian Jessie, I
can confirm it compiles  on Wheezy no Problem and I was able to install
hostapd from the Debian Repos no problem.

**Comment by singe** [comment]
I'll take a look. You could help speed it up by posting the output of ldd on the repo hostapd and a dpkg -S on the linked netlink lib?

**Comment by thesle3p** [comment]
ldd is:
linux-vdso.so.1 (0x00007ffefe5c8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff6f6e42000)
	libnl-3.so.200 => /lib/x86_64-linux-gnu/libnl-3.so.200 (0x00007ff6f6c25000)
	libnl-genl-3.so.200 => /lib/x86_64-linux-gnu/libnl-genl-3.so.200 (0x00007ff6f6a1f000)
	libnl-route-3.so.200 => /usr/lib/x86_64-linux-gnu/libnl-route-3.so.200 (0x00007ff6f67c7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff6f65c3000)
	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007ff6f6363000)
	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007ff6f5f68000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff6f5c67000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff6f58be000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff6f56a1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff6f7369000)



dpkg -S is:
hostapd: /usr/share/doc/hostapd/changelog.gz
hostapd: /usr/share/doc/hostapd/copyright
hostapd: /usr/share/doc/hostapd/examples/hostapd.radius_clients
hostapd: /usr/share/lintian/overrides/hostapd
hostapd: /usr/share/doc/hostapd
hostapd: /etc/default/hostapd
hostapd: /usr/share/doc/hostapd/examples/hostapd.eap_user.gz
hostapd: /usr/share/man/man1/hostapd_cli.1.gz
hostapd: /usr/share/doc/hostapd/README.Debian
hostapd: /usr/share/doc/hostapd/examples
hostapd: /usr/share/doc/hostapd/examples/hostapd.deny
hostapd: /etc/network/if-pre-up.d/hostapd
hostapd: /usr/share/doc/hostapd/NEWS.Debian.gz
hostapd: /usr/sbin/hostapd
hostapd: /usr/sbin/hostapd_cli
hostapd: /usr/share/doc/hostapd/examples/hostapd.wpa_psk
hostapd: /usr/share/doc/hostapd/changelog.Debian.gz
hostapd: /usr/share/doc/hostapd/examples/hostapd.accept
hostapd: /etc/init.d/hostapd
hostapd: /usr/share/man/man8/hostapd.8.gz
hostapd: /usr/share/doc/hostapd/examples/hostapd.conf.gz
hostapd: /etc/hostapd
hostapd: /etc/network/if-post-down.d/hostapd
hostapd: /etc/hostapd/ifupdown.sh

**Comment by Jessexd** [comment]
It will compile just fine on jessie, just uncomment this:
#CONFIG_LIBNL32=y

file location from git is: 
mana/hostapd-mana/hostapd/.config

**Comment by thesle3p** [comment]
I can confirm that that fixes this issue, thanks again!

**Comment by rhertzog** [comment]
It would be really nice if you could update hostapd-mana default configuration to use CONFIG_LIBNL32=y  (and then update the submodule here) and to update the instructions to say to use "libnl-3-dev" instead of "libnl-dev". The latter no longer exists on recent releases while the former exists for quite some time already.... (both in Kali and in Debian).

**Comment by Jessexd** [comment]
rhertzog, although Jessie is now stable and libnl-3* is now used. Many, MANY people still are using wheezy.

Kali I think uses wheezy (thus old netlink libs). I think aug 11 this year Kali will release. I think updating the readme will be better letting people know of this issue to prevent repeated issues showing up from new mana-toolkit users.

**Comment by rhertzog** [comment]
@Jessexd kali 1.x and wheezy have both libnl-dev and libnl-3-dev so the switch does not impact those distributions. And I know about the Kali release, I'm a Kali developer :)

**Comment by Jessexd** [comment]
oh, I thought libnl-3 couldnt be installed using basic wheezy repos without changing them to Jessie

guess imma wrong

**Comment by singe** [comment]
The latest release has Debian binary debs for those who can't compile.

**Comment by cardercvv** [comment]
Makefile:1036: recipe for target '../src/drivers/driver_nl80211.o' failed
make: *** [../src/drivers/driver_nl80211.o] Error 1

some help
