### ISSUE TITLE
Not clear on what dependancies are needed for Mana-Toolkit in the Readme.md

### ISSUE THREAD

**Issue by Jessexd** [sensepost/mana#33]
See in the readme file:
>If you're installing from git, you can use the following commands after you have grabbed the necessary dependencies:

However, it doesn't even list the necessary dependencies needed or optional dependencies in mana-toolkits readme.

This can be somewhat confusing to someone new to this or someone installing on another distro that isnt based on Debian or Ubuntu such as Arch.

Also would like to point out that there is no clear listing on what distros are supported.

**Comment by singe** [comment]
The ubutu installer script lists some dependencies. At the moment, Kali is the primary distro supported with Debian/Raspian supported on a best-effort basis. That said, there isn't much difficulty is porting to other distros. Pull requests welcome!
