### ISSUE TITLE
hostapd won't compile on jessie  ../src/drivers/driver_hostap.c:319:8: error: too few arguments to function ‘hostap_send_mlme’

### ISSUE THREAD

**Issue by pos-ei-don** [sensepost/mana#34]
I already read issue #32, but #CONFIG_LIBNL32=y is uncommented in my .config:
https://github.com/sensepost/mana/issues/32

This is the output I'm getting:

  CC  ../src/radius/radius_das.c
  CC  ../src/ap/accounting.c
  CC  ../src/ap/vlan_init.c
  CC  ctrl_iface.c
  CC  ../src/ap/ctrl_iface_ap.c
  CC  ../src/ap/iapp.c
  CC  ../src/ap/peerkey_auth.c
../src/drivers/driver_hostap.c: In function ‘hostap_send_eapol’:
../src/drivers/driver_hostap.c:319:8: error: too few arguments to function ‘hostap_send_mlme’
  res = hostap_send_mlme(drv, (u8 *) hdr, len, 0);
        ^
../src/drivers/driver_hostap.c:269:12: note: declared here
 static int hostap_send_mlme(void *priv, const u8 *msg, size_t len, int noack,
            ^
../src/drivers/driver_hostap.c: In function ‘hostap_sta_deauth’:
../src/drivers/driver_hostap.c:1055:9: error: too few arguments to function ‘hostap_send_mlme’
  return hostap_send_mlme(drv, (u8 *) &mgmt, IEEE80211_HDRLEN +
         ^
../src/drivers/driver_hostap.c:269:12: note: declared here
 static int hostap_send_mlme(void *priv, const u8 *msg, size_t len, int noack,
            ^
../src/drivers/driver_hostap.c: In function ‘hostap_sta_disassoc’:
../src/drivers/driver_hostap.c:1093:10: error: too few arguments to function ‘hostap_send_mlme’
  return  hostap_send_mlme(drv, (u8 *) &mgmt, IEEE80211_HDRLEN +
          ^
../src/drivers/driver_hostap.c:269:12: note: declared here
 static int hostap_send_mlme(void *priv, const u8 *msg, size_t len, int noack,
            ^
../src/drivers/driver_hostap.c: In function ‘wpa_driver_hostap_poll_client’:
../src/drivers/driver_hostap.c:1172:2: error: too few arguments to function ‘hostap_send_mlme’
  hostap_send_mlme(priv, (u8 *)&hdr, sizeof(hdr), 0);
  ^
../src/drivers/driver_hostap.c:269:12: note: declared here
 static int hostap_send_mlme(void *priv, const u8 *msg, size_t len, int noack,
            ^
../src/drivers/driver_hostap.c: In function ‘hostap_sta_disassoc’:
../src/drivers/driver_hostap.c:1095:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/drivers/driver_hostap.c: In function ‘hostap_sta_deauth’:
../src/drivers/driver_hostap.c:1057:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:922: recipe for target '../src/drivers/driver_hostap.o' failed

**Comment by Jessexd** [comment]
did you make sure libnl-genl-3-dev  and libnl-3-dev was installed?

**Comment by pos-ei-don** [comment]
Shure I did.

#dpkg-query -l 'libnl*'
ii  libnl-3-200:i386                   3.2.24-2               i386                   library for dealing with netlink sockets
ii  libnl-3-dev                        3.2.24-2               i386                   development library and headers for libnl-3
un  libnl-dev                          <keine>                <keine>                (keine Beschreibung vorhanden)
ii  libnl-genl-3-200:i386              3.2.24-2               i386                   library for dealing with netlink sockets - generic netlink
ii  libnl-genl-3-dev                   3.2.24-2               i386                   development library and headers for libnl-genl-3
ii  libnl-nf-3-200:i386                3.2.24-2               i386                   library for dealing with netlink sockets - netfilter interface
ii  libnl-nf-3-dev                     3.2.24-2               i386                   development library and headers for libnl-nf-3
ii  libnl-route-3-200:i386             3.2.24-2               i386                   library for dealing with netlink sockets - route interface
ii  libnl-route-3-dev                  3.2.24-2               i386                   development library and headers for libnl-route-3
un  libnl2-dev                         <keine>                <keine>                (keine Beschreibung vorhanden)
un  libnl3-dev                         <keine>                <keine>                (keine Beschreibung vorhanden)

**Comment by Jessexd** [comment]
try apt-get update && apt-apt get build-dep hostapd

**Comment by pos-ei-don** [comment]
thank you for the hint, it installed several additional packages (~200MB), but the error is still the same.
I did make clean && make.

**Comment by Jessexd** [comment]
try this:
find your driver_hostap.c and post it
apt-get install firmware-linux firmware-linux-nonfree
compile https://w1.fi/releases/hostapd-2.4.tar.gz
check if any errors to confirm whether or not it's mana-toolkits modified hostapd or not.

**Comment by pos-ei-don** [comment]
Thank you for your help!!!
This is the diff of the two files:
```Diff
diff /hostap/hostap/src/drivers/driver_hostap.c /mana-hostap/hostapd-2.4/src/drivers/driver_hostap.c
269,270c269
< static int hostap_send_mlme(void *priv, const u8 *msg, size_t len, int noack,
<                           unsigned int freq)
---
> static int hostap_send_mlme(void *priv, const u8 *msg, size_t len, int noack)
```

But I'm still geting an error on compilation, but i didn't have time to go further into it.
I will have a look at it tomorrow.

 CC  ../src/crypto/random.c
  CC  ../src/ap/wmm.c
  CC  ../src/ap/ap_list.c
  CC  ../src/ap/ieee802_11.c
  CC  ../src/ap/hw_features.c
  CC  ../src/ap/dfs.c
  CC  ../src/ap/ieee802_11_ht.c
  CC  ../src/ap/ieee802_11_vht.c
  CC  ../src/drivers/driver_common.c
  CC  ../src/ap/acs.c
/usr/bin/ld: cannot find -lnl
collect2: error: ld returned 1 exit status
Makefile:954: recipe for target 'hostapd' failed
make: *** [hostapd] Error 1

**Comment by pos-ei-don** [comment]
Di found another mininute to play with it: --> https://github.com/sensepost/mana/issues/32 solved the current provlem, so the solution for me was to take the driver_hostap.c from your mana-downloadlink
and uncomment 
#CONFIG_LIBNL32=y in /.config  as suggestes in #32.

**Comment by singe** [comment]
The error you got was related to being unable to link the netlink library. Have you got the library (not the source) installed? I see you posted above that libnl-genl-3-200 is installed, maybe check the output of ls /lib/*/libnl* ?

**Comment by pos-ei-don** [comment]
Sorry, I cann't test it as I sold the system where I wanted to use it...
