### ISSUE TITLE
Please make release with proper tag

### ISSUE THREAD

**Issue by sbrun** [sensepost/mana#36]
Hi,
It would be great if you could make tagged releases with "standard" versions (something like v2.0).
For kali we made snapshot of the git repository but it's better to have tagged releases: 
we have tools that monitors web pages listing release, and it works well with github pages showing git tags. Each time you will release a new tagged version (with a larger number than previous versions), we will be informed and we will be able to update quickly.
Thanks!

**Comment by singe** [comment]
Done.
