### ISSUE TITLE
Problems modifying configuration file

### ISSUE THREAD

**Issue by bamnsec** [sensepost/mana#43]
I have been working all night to get Mana to work with a TP Link WN722N, and keep failing.  What I notice is that whenever I change the hostapd-karma.conf file to listen on wlan2 it always defaults itself back to wlan0, which does not support master mode, and forces the entire attempt to fail.  Also, I have changed the driver to the driver indicated by airmon-ng and it keeps telling me that the driver cannot be found.  What am I doing wrong?

**Comment by Bryantp757** [comment]
chmod the file permissions, 777 or whatever you feel is appropriate. If your driver successfully loads when you run the script, give me a shout. I seem to be having issues
auto usb0
allow-hotplug usb0
iface usb0 inet dhcp

iface wlan0 inet dhcp

**Comment by theleestarr** [comment]
you need to edit the script for YOUR interface names.

output should look something like 

#!/bin/bash

upstream=eno1
phy=wlp3s0
conf=/etc/mana-toolkit/hostapd-mana.conf
hostapd=/usr/lib/mana-toolkit/hostapd

**Comment by singe** [comment]
As theleestarr said, the start-*.sh scripts modify the hostapd conf, so make sure you put the right interface in there otherwise changes to the conf will be overwritten.
