### ISSUE TITLE
make installation isssue 

### ISSUE THREAD

**Issue by sidjad** [sensepost/mana#46]
make -C hostapd-mana/hostapd/
make[1]: Entering directory '/root/mana/hostapd-mana/hostapd'
../src/drivers/driver_nl80211.c:19:31: fatal error: netlink/genl/genl.h: No such file or directory
 #include <netlink/genl/genl.h>
                               ^
compilation terminated.
Makefile:891: recipe for target '../src/drivers/driver_nl80211.o' failed
make[1]: *** [../src/drivers/driver_nl80211.o] Error 1
make[1]: Leaving directory '/root/mana/hostapd-mana/hostapd'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by blackHatMonkey** [comment]
The `/usr/include/netlink/genl/genl.h` header file is contained in the `libnl-dev` package. You can install it using `sudo apt-get install libnl-dev` commnad.

**Comment by sidjad** [comment]
sudo apt-get install libnl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libnl-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libnl-dev' has no installation candidate

**Comment by mw3demo** [comment]
sudo apt-get install libnl-3-dev

**Comment by brandontict** [comment]
I receive same error , I have installed libnl-3-dev, 

[root:/opt/hostapd-1.0-karma/hostapd]# sudo apt-get install libnl-3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnl-3-dev is already the newest version.
libnl-3-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.

**Comment by singe** [comment]
If you're going to use libnl32 you also need to edit hostapd's config file. The patch at https://github.com/sensepost/mana/pull/42/files should explain it.

**Comment by brandontict** [comment]
Thank you for the reply, I'll post my results.

**Comment by singe** [comment]
We've switched to libnl3 by default, and the binary debs in the last release are available if you're struggling to compile.

**Comment by weili1457355863** [comment]
I installed libnl-3-dev ,but hostapd: error while loading shared libraries: libnl.so.1: cannot open shared object file: No such file or directory

**Comment by weili1457355863** [comment]
can u tell me how to do

**Comment by singe** [comment]
This means you compiled with NL 2.0 *not* 3.0 support and it's looking for that lib. Edit .config to use libnl3.

**Comment by joker5bb** [comment]
I am also experiencing this issue, I have all dependencies installed and got CONFIG_LIBNL32=y set

**Comment by singe** [comment]
Can you list the libnl packages you have?

**Comment by joker5bb** [comment]
root@kali:~# dpkg -l | grep libnl
ii  libnl-3-200:armhf                    3.2.27-1+b1                       armhf        library for dealing with netlink sockets
ii  libnl-3-dev:armhf                    3.2.27-1+b1                       armhf        development library and headers for libnl-3
ii  libnl-genl-3-200:armhf               3.2.27-1+b1                       armhf        library for dealing with netlink sockets - generic netlink
ii  libnl-route-3-200:armhf              3.2.27-1+b1                       armhf        library for dealing with netlink sockets - route interface


Im also using the hostapd 2.6 brannch

**Comment by s0lst1c3** [comment]
@joker5bb @weili1457355863 

Try installing _nfnetlink-dev_ and _pkg-config_ using the following command:

`apt-get install nfnetlink-dev pkg-config`

I stumbled across this thread on Google after running into the same problem today trying to compile hostapd-2.6 for a similar project. Figured out the solution after reading the following post:

[https://ubuntuforums.org/showthread.php?t=2090758](https://ubuntuforums.org/showthread.php?t=2090758)

@singe If this works @joker5bb  and @weili1457355863 , it might be worth adding those packages to the project dependencies.

**Comment by joker5bb** [comment]
The correct dependencies are libnl-3-dev and libnl-genl-3-dev

**Comment by getr00t** [comment]
@singe @joker5bb @joker5bb @mw3demo also encountered the same problem when installing hostapd-wpe on Raspberry Pi. How should I solve it?
System version: Debian GNU/Linux 11 (bullseye)  No desktop version system

I want to study airgeddon on Raspberry Pi 4 OS, but it says hostapd-wpe is missing. I found that hostapd dependency is installed by default on Raspberry Pi system. Is hostapd not equivalent to hostapd-wpe? How can I install hostapd-wpe successfully? Thank you.

![1265](https://github.com/sensepost/mana/assets/12257416/57e36384-fc0a-4fbf-8886-b8f7111ac1df)
![error](https://github.com/sensepost/mana/assets/12257416/19b33b4c-fea4-4ad5-8406-dc6e65bfa385)
![libnl](https://github.com/sensepost/mana/assets/12257416/33ddca6c-49a8-4434-81ac-cc552ac14cca)
