### ISSUE TITLE
error no 1

### ISSUE THREAD

**Issue by sidjad** [sensepost/mana#47]
# Install the hostapd binary
install -m 755 hostapd-mana/hostapd/hostapd /usr/lib/mana-toolkit/
install: cannot stat ‘hostapd-mana/hostapd/hostapd’: No such file or directory
Makefile:6: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by Chronomy** [comment]
I have the same problem someone help us please

**Comment by singe** [comment]
It looks like you didn't initalise submodules, run the following in your mana directory and try again:
git submodule init
git submodule update

Alternativley, just apt-get install mana-toolkit in kali and get the binary.
