### ISSUE TITLE
Error when make

### ISSUE THREAD

**Issue by rizkyherliana** [sensepost/mana#48]
/usr/bin/ld: cannot find -lnl-genl-3
collect2: error: ld returned 1 exit status
Makefile:917: recipe for target 'hostapd' failed
make[1]: *** [hostapd] Error 1
make[1]: Leaving directory '/home/pi/mana/hostapd-mana/hostapd'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jakuta-tech** [comment]
apt-get install libnl-genl-3-dev
