### ISSUE TITLE
No Captive portal in nat-full

### ISSUE THREAD

**Issue by tAHU363** [sensepost/mana#50]
I'm to understand that the captive portal allows one to set the cert/autoconfigure so no warnings are thrown during visiting various websites as well as capturing credentials, and that nat-full has "all the bells and whistles", but no captive portal. Is there a way to add the captive portal to nat-full, redirecting them tot he internet once logged in with a gmail/facebook etc account?

**Comment by singe** [comment]
There is. Most us nodogsplash to do it, an existing captive portal tool. There isn't an out of the box configuration however.
