### ISSUE TITLE
error in mana menu when run

### ISSUE THREAD

**Issue by tAHU363** [sensepost/mana#51]
output is 

root@kali:~# '/root/Desktop/MANA/run-mana/mana-menu.sh'
Do you want to intercept victim communication to the Internet or fake the Internet? (nat/noupstream)
nat
/root/Desktop/MANA/run-mana)/mana-menu.sh: line 240: syntax error near unexpected token `fi'
/root/Desktop/MANA/run-mana//mana-menu.sh: line 240: `fi'

I am running kali 2.0 fully updated with the latest version of mana. How do I fix this?

**Comment by singe** [comment]
Hi

It looks like you're using some sort of menu front end. That isn't part of mana that I wrote not included with Kali that I know. Where did you get it?

Try clone mana anew following the instructions at https://github.com/sensepost/mana

**Comment by tAHU363** [comment]
Its included inthe apt repo package for kali (2.0 at least) as well as kali nethunter

**Comment by yomoenco** [comment]
at the end there is an empty "else" and at line 230  "type" gets read but in the next line $output is being tested, should be $type I PRESUME

**Comment by strasharo** [comment]
I get the same error in latest Kali, both using the package from the distribution and checking out the latest source from git:

```
root@kalif:~/mana/run-mana# ./mana-menu.sh 
Do you want to intercept victim communication to the Internet or fake the Internet? (nat/noupstream)
nat
./mana-menu.sh: line 240: syntax error near unexpected token `fi'
./mana-menu.sh: line 240: `fi'
root@kalif:~/mana/run-mana# 

```

**Comment by strasharo** [comment]
Besides the errors mentioned by @yomoenco , there's also the following syntax error:
`./mana-menu.sh: line 215: [: 1 packets transmitted, 1 received, 0% packet loss, time 0ms: integer expression expected
`
I guess this: https://github.com/sensepost/mana/blob/master/run-mana/mana-menu.sh#L214 
`ntst="$(ping -c1 8.8.8.8| grep received | sed 's/.*1 packets received.*/1/')"`

Should become something like this to work:
`ntst="$(ping -c1 8.8.8.8| grep received | awk '{print $4}')"`

**Comment by singe** [comment]
Heya. Sorry mana-menu.sh was started but never finished. I should have said, I mistakenly assumed no one would see/use it ;) Feel free to help finish it?

**Comment by aeb5005** [comment]
Oh! So that's why this isn't working, glad I found this.

**Comment by strasharo** [comment]
Okay, I'll try to finish it in the weekend.

**Comment by donwildman** [comment]
Hi Guys,

This line:
ntst="$(ping -c1 8.8.8.8| grep received | sed 's/.*1 packets received.*/1/')"
change to:
ntst="$(ping -c1 8.8.8.8| grep received | sed 's/.*1 received.*/1/')"
to fix the error above.

Fantastic tool guys, I can help fix the mana-menu.sh if it hasn't already been done.

**Comment by donwildman** [comment]
Line 230, change 

> read type 

to 

> read  output

then remove the last

> ELSE
on line 238

**Comment by singe** [comment]
Kali has removed it from the package. It's a work in progress/on hold.
