### ISSUE TITLE
How to respond all probe request (karma Mode) with mana toolkit?

### ISSUE THREAD

**Issue by jamesmith-git** [sensepost/mana#53]
Hii

Is it possible to respond to all probe requests by mana toolkit.

During working with mana toolkit, we need to mention our Rouge SSID in hostapd-karma.conf like:

interface=wlan0
bssid=00:11:22:33:44:00
driver=nl80211
ssid=Internet
channel=6

If we work with these settings, only one AP broadcast with named "Internet" and if victim connects with our AP, then only we're able to sniff data and run other modules. 

How can we make it working so that it'll reply to all devices Broadcasted probe requests.

Other issue is:

With this Karma mode, only open WiFi connects to our Rouge AP automatically. How can we make it working so that secured AP also connects with the same ESSID Rouge AP generated by Mana toolkit.

I hope Sensepost staff is the right one who helps in these problems and make it working. 
If any other member aslo helps in the same, It'll be a helping hand to complete my college project on WiFi Penetration Testing.

Kind Regards
James

**Comment by singe** [comment]
Hello

The karma=true directive in the hostapd config controls whether mana will respond to all broadcast probes. 

As for responding to secure networks, check out the hostapd-karma-eaponly and eap-all configs for examples.

**Comment by jamesmith-git** [comment]
Hello Sir,

Thanks for the help. I'll try on theis solution and hope so it works fine with me. One more question can we make it working with openwrt?

**Comment by jamesmith-git** [comment]
How can we install mana-toolkit in openwrt

**Comment by singe** [comment]
There's a discussion of porting to openwrt over at https://github.com/sensepost/hostapd-mana/issues/3 closing this in the meantime
