### ISSUE TITLE
Sslstrip2 not working on Gmail (Chrome Browser)

### ISSUE THREAD

**Issue by jamesmith-git** [sensepost/mana#54]
Hello Sir

Other services like facebook, live.com etc working fine on HSTS sslstripping on Chrome browser. But when we are opening "gmail.com on Google Chrome" the page stops responding. 

Is the SSLSTRIP2 + Dns2proxy method also stopped or am I doing mistake somewhere.

**Comment by singe** [comment]
Chrome does cert pinning for gmail and sslstrip won't work.
