### ISSUE TITLE
Hardware requirement question: Is only one wireless device needed to function as an AP?

### ISSUE THREAD

**Issue by aeb5005** [sensepost/mana#56]
As the title states, I'm wondering if I only need one wifi device (such as the recommended Alfa AWUS050NH) to function as a malicious access point. Basically, the idea is I want to use mana on my desktop and see if I can get an older phone I have (nexus 4) to connect to the malicious mana access point instead of my benign normal home router. I have no wireless card in my desktop right now, so I just wanted to make sure I only need to buy one device. Thanks!

**Comment by singe** [comment]
One device is fine.
