### ISSUE TITLE
Not redirecting Traffic to Portal

### ISSUE THREAD

**Issue by ApatheticEuphoria** [sensepost/mana#57]
I installed this on Kali 2.0 using the apt-get command.
Made the necessary changes to the config files... 
Then copied the contents of Portal to the www folder.
When i start the rogue Ap with ./start-noupstream.sh the traffic is not being redirected to the portal...Also i see a notification for signing in to access the web,but when i click it nothing loads up,just a white screen.

Am i missing something or doing something wrong,or is this some sort of bug?

**Comment by singe** [comment]
We'll need more details to debug that. You shouldn't need to copy anything the package will put it in the right place. Is Apache running, is the site enabled, did you copy the portals site config, does it match the location you copied the portal to?

**Comment by ApatheticEuphoria** [comment]
Far as i know Apache is running(Help me check properly?)...How to enable the site,or what do you mean by that...you just said i shouldnt need to copy anything,lol,then you ask if i copied the sites config...again,can you please explain. Sorry,im a bit new to this. If you want to skype maybe to help me clear up some issues,rather than here, my skype is apathetic_euphoria

**Comment by 3lk3n1313** [comment]
same error? any solutions? thx

**Comment by ApatheticEuphoria** [comment]
@3lk3n1313 Nope,still havent fixed it yet. I think there needs to be more documentation on how to actually use all the different Mana attack types to be honest.

**Comment by 3lk3n1313** [comment]
i think the error it's in the tinyproxy conf or in the dnsspoof, maybe i'm not sure

**Comment by zerocolTHS** [comment]
I am also having the same issue when using start-noupstream.sh, traffic just isn't getting redirected tp the portal
If i goto to 127.0.0.1 it show's fine so files are defo in correct place.
Fully updated kali
4.4.0-kali1-686-pae #1 SMP Debian 4.4.6-1kali1 (2016-03-18) i686 GNU/Linux

Thanks i hope you can help us with this.

**Comment by singe** [comment]
Can you test with the new version? Also, please make sure nginx is disabled, as there were some issues with conflicts there.
