### ISSUE TITLE
Script outputs too much information

### ISSUE THREAD

**Issue by DrDinosaur** [sensepost/mana#7]
The start-nat-full.sh script outputs far too much information to the terminal. It is easy to have it output thousands or tens of thousands of lines, much of which is repeated, not useful, or time consuming to understand, interpret, or process. I would strongly suggest parsing the output to make it concise, useful, and easy to process. Alternatively, or additionally, a web interface could nicely display the information necessary. Presently, I don't easily see the devices connected or what is really going on. I mainly see tons of responses blasted out or large amounts of sslsplit information. Making the information easier to consume and process would be a great improvement.

**Comment by singe** [comment]
I've slowly started doing this. Trying to update specific stuff to specific logs.
