### ISSUE TITLE
Mana creates several access points instead of just the one specified

### ISSUE THREAD

**Issue by nono21** [sensepost/mana#81]
Hello guys, I'm using Kali Linux under VirtualBox on a MacBook. I'm having this issue that whenever I start mana-toolkit by running ./start-nat-simple.sh It creates the access point I specified but also creates several access points using the list of saved wifi networks I've connected to in the past... Anyone with a similar issue? How is this possible??
Thanks guys

**Comment by singe** [comment]
Heya, that's what it's supposed to do. If you'd like to read more on it, you can see the original talk at https://youtu.be/i2-jReLBSVk You can disable it by setting enabled_mana=0 in the config, or just use vanilla hostapd.

**Comment by nono21** [comment]
Thanks a lot singe!
