### ISSUE TITLE
Can't get captive portal in start-noupstream.sh

### ISSUE THREAD

**Issue by BigJ80** [sensepost/mana#83]
Sorry to post an issue that's already been asked multiple times but I can't really figure out what's going wrong with this script and I'm not able to find any solutions here and/or the internet.
All tutorials on youtube are complete junk too.

I'm having same issue on a brand-new Kali2017 and Nethunter 3 on nexus5x
My AP is up on wlan1 with a TPLink TL wn722.
Fixed the dnsmasq line since "-i" argument was missing.
Checked dnsmasq dhcp configuration (why is it assigning dns 8.8.8.8 when no connection is expected?)
Verified apache2 configuration: everything ok, all mana sites enabled including portal.
Verified all config files.
Dnsspoof starts correctly, spoofing to 10.0.0.1

As any device connects to the  rogue AP, looks  like the requests are not routed correctly at all, and captive portal is not loaded after wifi authentication when the WPad address should be invoked by the client.
I don't understand if dnsspoof is doing his job (it logs the DNS requests to 8.8.8.8, is it spoofing such requests to 10.0.0.1  as it is supposed to do ? )
Also, Apache2  is running, but looking at access.log I can't get any request by the wifi-connected devices.

If anybody had similar issues *and* a solution please let me know.

S.

**Comment by singe** [comment]
The DNS setting to 8.8.8.8 doesn't matter as the firewall rules reroute all DNS traffic.

I'd need more debugging info to work out why the captive portal isn't loading. But this repository has been deprecated. Check out (w1f1.net)[https://w1f1.net] for the latest tooling.

In particular [bettercap](http://bettercap.org) and [berate-ap](https://github.com/sensepost/berate_ap) can do captive portals. The core of mana, [hostapd-mana](https://github.com/sensepost/hostapd-mana) is still under active development.
