### ISSUE TITLE
MANA still redirecting probes with enable_mana=0 and ACLs On

### ISSUE THREAD

**Issue by selicia** [sensepost/mana#87]
I'm trying to run host-apd mana (v2.3) and have the network behave like a "standard AP" using the **enable_mana=0** setting. However, when I run it I notice that it still redirects network probes as seen below. I've also tried setting the MAC ACLs (whitelist & blacklist) but they also don't appear to have any effect. Is there anything else I should be doing to disable MANA, or is my configuration file not getting fully parsed? For reference I put all of my configuration files on pastebin. Let me know if you need any other information, and thank you for your help!

~ Cheers

```
/usr/lib/mana-toolkit/hostapd /root/config/mana/hostapd-mana.conf 
Configuration file: /root/config/mana/hostapd-mana.conf
Using interface wlan0 with hwaddr 00:11:22:33:44:00 and ssid "Internet"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
MANA - Directed probe request for foreign SSID 'Netgear' from 64:bc:0c:42:b7:31
```

**OS**: 4.12.0-kali1-amd64
**hostapd-mana.conf:** https://pastebin.com/jhkZP0m8
**hostapd.accept**: https://pastebin.com/5zvEWAaF
**hostapd.deny**: https://pastebin.com/Dqj5eCLz

**Comment by singe** [comment]
I’ll need to confirm it. But I think it’s just alerting on the foreign SSID, not responding to it.

**Comment by selicia** [comment]
Did some more testing. You're right, it's just alerting. The whitelist/blacklist settings are also working properly so I'm closing this. Thanks!
