### ISSUE TITLE
Kali 2018.1 support

### ISSUE THREAD

**Issue by k0mand1r** [sensepost/mana#96]
The kali-install.sh script does not properly install the toolkit. 
When I download the github repo; init; update; make; it errors on the make part.
This results in the /usr/share/mana-toolkit/run-menu/ directory being empty most likely.

Kind regards,

**Comment by rand99** [comment]
after
```
./kali-install.sh
apt-get install libssl1.0-dev libnl-genl-3-dev libnl-3-dev
```



i end up with 

`root@kali:~/mana# make
make -C hostapd-mana/hostapd/
make[1]: Entering directory '/root/mana/hostapd-mana/hostapd'
../src/eap_common/eap_pwd_common.o: In function `compute_password_element':
/root/mana/hostapd-mana/hostapd/../src/eap_common/eap_pwd_common.c:220: undefined reference to `BN_is_odd'
collect2: error: ld returned 1 exit status
Makefile:917: recipe for target 'hostapd' failed
make[1]: *** [hostapd] Error 1
make[1]: Leaving directory '/root/mana/hostapd-mana/hostapd'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Jinovas** [comment]
make sure to be compiling hostapd 2.6 branch which i believe is different than the one in the actual toolkit. Either way, i had more success and less issues doing the following:

clone mana-toolkit 
remove the hostapd directory in the mana-toolkit directory
clone this hostapd in the same directory: https://github.com/sensepost/hostapd-mana.git

**Comment by singe** [comment]
Like @Jinovas said, can you try the latest version of (hostapd-mana)[https://github.com/sensepost/hostapd-mana] and see if that works better for you. 

This repository has been deprecated. Check out (w1f1.net)[https://w1f1.net] for the latest tooling.

I'm going to close the issue here, but feel free to reopen it on hostapd-mana's repo with debugging info.

**Comment by Pectrigger** [comment]
I did as you instructed but look at what I got
../src/eap_common/eap_pwd_common.o: In function `compute_password_element':
/home/pec/mana/hostapd-mana/hostapd/../src/eap_common/eap_pwd_common.c:220: undefined reference to `BN_is_odd'
collect2: error: ld returned 1 exit status
Makefile:917: recipe for target 'hostapd' failed
make: *** [hostapd] Error 1
