### ISSUE TITLE
why is mana trying to find start-nat-full-lollipop.sh? 

### ISSUE THREAD

**Issue by burntGit** [sensepost/mana#99]
I am running Nethunter so this may be better suited over there, depending on what the correct solution turns out to be.

Android 8.1.0
Oxygen 5.1.3
Kali Nethunter "Burgerhunter" Kernel installed over stock oos
TWRP codeworkx 3.2
Magisk 16.7
Mana-toolkit 1.3.1-0kali

I am trying to run the mana-toolkit from the nethunter apk on my android. Every time that I try to start mana-nat-simple, my nethunter terminal opens and looks for "start-nat-full-lollipop.sh" a script that is not in the run-mana directory. Is this a version issue with my chroot? I have tried installing from apt-get after purging mana-toolkit, (and fruitywifi just incase) with no luck... on one install i tried, i compiled mana-toolkit from source but it threw way too many errors to list.

Here is the error it throws in cli:

bash: /usr/share/mana-toolkit/run-mana/start-nat-full-lollipop.sh
: No such file found

when i cd to run-mana the following scripts are listed:

fire-lamb-view.sh
start-nat-full.sh
start-nat-simple.sh
start-noupstream-all.sh
start-noupstream-eap.sh
start-noupstream-eaponly.sh
start-noupstream.sh

how can i point mana towards the correct script?

this is my first post here.

Thank you for any assistance

**Comment by burntGit** [comment]
I am running Nethunter so this may be better suited over there, depending on what the correct solution turns out to be.


Android 8.1.0
Oxygen 5.1.3
Kali Nethunter "Burgerhunter" Kernel installed over stock oos
TWRP codeworkx 3.2
Magisk 16.7
Mana-toolkit 1.3.1-0kali

I am trying to run the mana-toolkit from the nethunter apk on my android. Every time that I try to start mana-nat-simple, my nethunter terminal opens and looks for "start-nat-full-lollipop.sh" a script that is not in the run-mana directory. Is this a version issue with my chroot? I have tried installing from apt-get after purging mana-toolkit, (and fruitywifi just incase) with no luck... on one install i tried,  i compiled mana-toolkit from source but it threw way too many errors to list here. 

bash: /usr/share/mana-toolkit/run-mana/start-nat-full-lollipop.sh
: No such file found

when i cd to run-mana the following scripts are listed:

fire-lamb-view.sh
start-nat-full.sh
start-nat-simple.sh
start-noupstream-all.sh
start-noupstream-eap.sh
start-noupstream-eaponly.sh
start-noupstream.sh

how can i point mana towards the correct script? 

this is my first post here.

Thank you for any assistance

**Comment by singe** [comment]
lolipop is nethunter specific and isn't included on this repository.

Also, this repository has been deprecated. Check out (w1f1.net)[https://w1f1.net] for the latest tooling.
